from yacs.config import CfgNode as CN

_C = CN()
_C.TIMESTAMP = 0
_C.MODEL = CN()
_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.NAME = "ViT-B/16"

_C.TriMPL = CN()
_C.TriMPL.PREC = "fp16"
_C.TriMPL.MODE = "normal"
_C.TriMPL.N_VIEW = 3
_C.TriMPL.N_CTX = 8
_C.TriMPL.ORTH_LAMBDA = 1.0

_C.OPTIM = CN()
_C.OPTIM.NAME = "sgd"
_C.OPTIM.LR = 2e-3
_C.OPTIM.MAX_EPOCH = 20
_C.OPTIM.WEIGHT_DECAY = 5e-4
_C.OPTIM.MOMENTUM = 0.9
_C.OPTIM.SGD_DAMPENING = 0
_C.OPTIM.SGD_NESTEROV = False
_C.OPTIM.WARMUP_TYPE = "CONST"
_C.OPTIM.WARMUP_EPOCH = 2
_C.OPTIM.MIN_LR = 1e-5

_C.DATASET = CN()
_C.DATASET.ROOT = "DATA"
_C.DATASET.TRN = 0.5
_C.DATASET.VAL = 0.2
_C.DATASET.TRAIN = ""
_C.DATASET.TESTS = []
_C.DATASET.NUM_SHOTS = 0

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 8
_C.DATALOADER.TRAIN = CN()
_C.DATALOADER.TRAIN.BATCH_SIZE = 2

_C.DATALOADER.TEST = CN()
_C.DATALOADER.TEST.BATCH_SIZE = 10

_C.SEED = 2023
_C.OUTPUT_DIR = "output"


def get_cfg_defaults():
    return _C.clone()
